services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  mock-webhook:
    build:
      context: .
      dockerfile: packages/mock-webhook/Dockerfile
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
    restart: unless-stopped 