global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    static_configs:
      - targets: ["api-gateway:3000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "webhook-manager"
    static_configs:
      - targets: ["webhook-manager:4000"]
    metrics_path: "/metrics"
    scrape_interval: 30s

  - job_name: "mock-webhook"
    static_configs:
      - targets: ["mock-webhook:5000"]
    metrics_path: "/stats"
    scrape_interval: 30s
